# frozen_string_literal: true

require "time"

module Gemkanbino
  # Story export functionality
  class StoryExporter
    attr_reader :pastel

    def initialize
      @pastel = Pastel.new
    end

    def export(story_data, format = "markdown", destination = nil)
      Utils::StoryValidator.validate_export_format(format)

      case format.to_s.downcase
      when "markdown"
        export_as_markdown(story_data, destination)
      when "html"
        export_as_html(story_data, destination)
      when "pdf"
        export_as_pdf(story_data, destination)
      when "txt"
        export_as_text(story_data, destination)
      else
        raise Exceptions::StoryExportError, "Unsupported format: #{format}"
      end
    end

    def list_supported_formats
      {
        "markdown" => "Markdown format (.md)",
        "html" => "HTML format (.html)",
        "pdf" => "PDF format (.pdf)",
        "txt" => "Plain text format (.txt)"
      }
    end

    private

    def export_as_markdown(story_data, destination)
      content = format_as_markdown(story_data)
      file_path = get_destination_path(destination, story_data[:title], "md")

      File.write(file_path, content)
      file_path
    end

    def export_as_html(story_data, destination)
      content = format_as_html(story_data)
      file_path = get_destination_path(destination, story_data[:title], "html")

      File.write(file_path, content)
      file_path
    end

    def export_as_text(story_data, destination)
      content = format_as_text(story_data)
      file_path = get_destination_path(destination, story_data[:title], "txt")

      File.write(file_path, content)
      file_path
    end

    def export_as_pdf(story_data, destination)
      # Try to use system tools for PDF generation
      begin
        # First generate HTML
        html_content = format_as_html(story_data)
        html_file = get_destination_path(nil, story_data[:title], "html")
        File.write(html_file, html_content)

        # Try different PDF generation methods
        pdf_file = get_destination_path(destination, story_data[:title], "pdf")

        if system("which wkhtmltopdf > /dev/null 2>&1")
          system("wkhtmltopdf #{html_file} #{pdf_file} 2>/dev/null")
          File.delete(html_file) if File.exist?(pdf_file)
        elsif system("which pandoc > /dev/null 2>&1")
          system("pandoc #{html_file} -o #{pdf_file} 2>/dev/null")
          File.delete(html_file) if File.exist?(pdf_file)
        elsif system("which chrome > /dev/null 2>&1") || system("which chromium > /dev/null 2>&1")
          chrome_cmd = system("which chrome > /dev/null 2>&1") ? "chrome" : "chromium"
          system("#{chrome_cmd} --headless --print-to-pdf=#{pdf_file} file://#{File.expand_path(html_file)} 2>/dev/null")
          File.delete(html_file) if File.exist?(pdf_file)
        else
          File.delete(html_file)
          raise Exceptions::StoryExportError, "No PDF generation tool found. Please install wkhtmltopdf, pandoc, or Chrome/Chromium"
        end

        if File.exist?(pdf_file)
          pdf_file
        else
          raise Exceptions::StoryExportError, "Failed to generate PDF"
        end
      rescue => e
        raise Exceptions::StoryExportError, "PDF export failed: #{e.message}"
      end
    end

    def format_as_markdown(story_data)
      metadata = story_data[:metadata]
      content = ""

      # Title and metadata
      content += "# #{metadata['title']}\n\n"

      content += "**Story Information**\n"
      content += "- *Template:* #{metadata['template']}\n"
      content += "- *Created:* #{Time.parse(metadata['created_at']).strftime('%Y-%m-%d %H:%M:%S')}\n"
      content += "- *Chapters:* #{metadata['chapters']}\n"
      content += "- *Word Count:* #{metadata['word_count']}\n"

      if metadata['characters'] && !metadata['characters'].empty?
        content += "- *Characters:* #{metadata['characters'].join(', ')}\n"
      end

      if metadata['genres'] && !metadata['genres'].empty?
        content += "- *Genres:* #{metadata['genres'].join(', ')}\n"
      end

      if metadata['tags'] && !metadata['tags'].empty?
        content += "- *Tags:* #{metadata['tags'].join(', ')}\n"
      end

      content += "\n---\n\n"

      # Chapters
      story_data[:chapters].each_with_index do |chapter, index|
        content += "## Chapter #{index + 1}: #{chapter[:title]}\n\n"
        content += "#{chapter[:content]}\n\n"
      end

      # Footer
      content += "---\n\n"
      content += "*Generated by Gemkanbino on #{Time.now.strftime('%Y-%m-%d %H:%M:%S')}*\n"

      content
    end

    def format_as_html(story_data)
      metadata = story_data[:metadata]

      html = <<~HTML
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>#{metadata['title']}</title>
          <style>
            body {
              font-family: 'Georgia', serif;
              line-height: 1.6;
              max-width: 800px;
              margin: 0 auto;
              padding: 20px;
              background-color: #f9f9f9;
            }
            h1 {
              color: #2c3e50;
              border-bottom: 3px solid #3498db;
              padding-bottom: 10px;
            }
            h2 {
              color: #34495e;
              margin-top: 30px;
              border-bottom: 1px solid #bdc3c7;
              padding-bottom: 5px;
            }
            .metadata {
              background-color: #ecf0f1;
              padding: 15px;
              border-radius: 5px;
              margin-bottom: 30px;
            }
            .metadata dt {
              font-weight: bold;
              color: #2c3e50;
            }
            .metadata dd {
              margin-bottom: 10px;
            }
            .chapter {
              margin-bottom: 40px;
            }
            .footer {
              text-align: center;
              font-style: italic;
              color: #7f8c8d;
              margin-top: 40px;
              border-top: 1px solid #bdc3c7;
              padding-top: 20px;
            }
          </style>
        </head>
        <body>
          <h1>#{metadata['title']}</h1>

          <div class="metadata">
            <dl>
              <dt>Template:</dt>
              <dd>#{metadata['template']}</dd>

              <dt>Created:</dt>
              <dd>#{Time.parse(metadata['created_at']).strftime('%Y-%m-%d %H:%M:%S')}</dd>

              <dt>Chapters:</dt>
              <dd>#{metadata['chapters']}</dd>

              <dt>Word Count:</dt>
              <dd>#{metadata['word_count']}</dd>
      HTML

      if metadata['characters'] && !metadata['characters'].empty?
        html += "<dt>Characters:</dt><dd>#{metadata['characters'].join(', ')}</dd>"
      end

      if metadata['genres'] && !metadata['genres'].empty?
        html += "<dt>Genres:</dt><dd>#{metadata['genres'].join(', ')}</dd>"
      end

      if metadata['tags'] && !metadata['tags'].empty?
        html += "<dt>Tags:</dt><dd>#{metadata['tags'].join(', ')}</dd>"
      end

      html += <<~HTML
            </dl>
          </div>
      HTML

      # Chapters
      story_data[:chapters].each_with_index do |chapter, index|
        html += <<~HTML
          <div class="chapter">
            <h2>Chapter #{index + 1}: #{chapter[:title]}</h2>
            <div class="content">
              #{format_content_as_html(chapter[:content])}
            </div>
          </div>
        HTML
      end

      # Footer
      html += <<~HTML
          <div class="footer">
            <p>Generated by Gemkanbino on #{Time.now.strftime('%Y-%m-%d %H:%M:%S')}</p>
          </div>
        </body>
        </html>
      HTML

      html
    end

    def format_as_text(story_data)
      metadata = story_data[:metadata]
      content = ""

      # Title
      content += "#{metadata['title']}\n"
      content += "=" * metadata['title'].length + "\n\n"

      # Metadata
      content += "Story Information:\n"
      content += "-" * 20 + "\n"
      content += "Template: #{metadata['template']}\n"
      content += "Created: #{Time.parse(metadata['created_at']).strftime('%Y-%m-%d %H:%M:%S')}\n"
      content += "Chapters: #{metadata['chapters']}\n"
      content += "Word Count: #{metadata['word_count']}\n"

      if metadata['characters'] && !metadata['characters'].empty?
        content += "Characters: #{metadata['characters'].join(', ')}\n"
      end

      if metadata['genres'] && !metadata['genres'].empty?
        content += "Genres: #{metadata['genres'].join(', ')}\n"
      end

      if metadata['tags'] && !metadata['tags'].empty?
        content += "Tags: #{metadata['tags'].join(', ')}\n"
      end

      content += "\n" + "=" * 50 + "\n\n"

      # Chapters
      story_data[:chapters].each_with_index do |chapter, index|
        content += "CHAPTER #{index + 1}: #{chapter[:title].upcase}\n"
        content += "-" * (chapter[:title].length + 13) + "\n\n"
        content += "#{chapter[:content]}\n\n"
      end

      # Footer
      content += "=" * 50 + "\n"
      content += "Generated by Gemkanbino on #{Time.now.strftime('%Y-%m-%d %H:%M:%S')}\n"

      content
    end

    def format_content_as_html(content)
      # Simple text to HTML conversion
      content.gsub(/\n\n+/, '</p><p>')
             .gsub(/\n/, '<br>')
             .prepend('<p>')
             .concat('</p>')
    end

    def get_destination_path(destination, title, format)
      if destination
        # Use provided destination
        if destination.end_with?(".#{format}")
          destination
        else
          File.join(destination, sanitize_filename(title) + ".#{format}")
        end
      else
        # Default to current directory
        File.join(Dir.pwd, sanitize_filename(title) + ".#{format}")
      end
    end

    def sanitize_filename(filename)
      filename.gsub(/[^a-zA-Z0-9\s\-_]/, '')
             .gsub(/\s+/, '_')
             .gsub(/_+/, '_')
             .gsub(/^_|_$/, '')
             .downcase
    end
  end
end